### PR TITLE
docs: Make config version 2.

### LINKED ISSUE #14: Add a `.readthedocs.yml` config file
The readthedocs build are complaining with;
image

So we should probably add a `.readthedocs.yml` config file. The config file format is described @ https://docs.readthedocs.io/en/stable/config-file/v2.html

### PR DESCRIPTION
**Pull request by mithro**
Remove unsupported config values.

Fixes #14.

Signed-off-by: Tim 'mithro' Ansell <tansell@google.com>

### CODE REVIEW

**Comment by mithro** [comment]
@mohanad0mohamed - This pull request fixes the config file that you added in https://github.com/google/open-source-pdks/pull/20 to actually work correctly. See the documentation at https://docs.readthedocs.io/en/stable/config-file/v2.html

**Review by mohanad0mohamed — APPROVED** [review]
I was really into this but as I commented earlier on another pull request, I was following the same configurations as Skywater pdk. 
Anyway, LGTM.

**Comment by atorkmabrains** [comment]
@mohanad0mohamed The doc build doesn't seem to build the documentation correctly?

**Comment by mohanad0mohamed** [comment]
@atorkmabrains The build won't be successful until all warnings are fixed.
I have made pull requests for this issue #18 to fix these warnings.

**Pull request merged**
